version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image:  wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "users.create:1:1, users.findAll:1:1, users.findOne:1:1, users.update:1:1, users.delete:1;1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped